### PR TITLE
server.cpp: add dtw

### PR DESCRIPTION
**Pull request by eschmidbauer**

### CODE REVIEW

**Comment by eschmidbauer** [comment]
@felrock @ggerganov 
Any chance we can get this merged?

**Comment by felrock** [comment]
Could you remove your linting, it's not clear what you are actually changing, thanks

**Comment by eschmidbauer** [comment]
> Could you remove your linting, it's not clear what you are actually changing, thanks

Sure, i know it can obscure the changes, that is why i put it in a [separate commit](https://github.com/ggerganov/whisper.cpp/pull/1983/commits/b40cb896ad798bb4616f22addffdf2e8d93b419d)

But i will rebase and disable linting in my IDE, thanks for the feedback

**Comment by eschmidbauer** [comment]
created new [PR](https://github.com/ggerganov/whisper.cpp/pull/2044)

**Pull request closed without merging**
