### PR TITLE
Add a new param to set the self attn text context factor

### PR DESCRIPTION
**Pull request by WilliamTambellini**
Add an env var to set the text context factor
WHISPER_SELFATTN_CACHE_TEXT_CTX_FACTOR
same default to 3.
Resolve:
https://github.com/ggerganov/whisper.cpp/issues/2334

### CODE REVIEW

**Comment by amoskahiga** [comment]
Thanks for the fix! Looks good to me.

**Comment by WilliamTambellini** [comment]
@aderbedr FYI

**Review by aderbedr — APPROVED** [review]
lgtm

**Comment by matiaslin** [comment]
Great! This looks good to me.

**Comment by WilliamTambellini** [comment]
@ggerganov ?

**Comment by ggerganov** [comment]
It's better to avoid the environment variable. Should implement this by adding a `int max_decoders` parameter to `whisper_context_params` and using it for the `factor`.

**Comment by WilliamTambellini** [comment]
ok @ggerganov 
I ve reimplemented and repushed.
Please re-review.
best

**Comment by ggerganov** [comment]
@WilliamTambellini I've pushed an alternative fix. Can you give it a try: https://github.com/ggerganov/whisper.cpp/pull/2443

**Comment by ggerganov** [comment]
Superseded by #2443

**Pull request closed without merging**
