### PR TITLE
whisper : add support for large v3

### PR DESCRIPTION
**Pull request by ggerganov**
**NOTE: re-download `ggml-large.bin` to get the v3 version**

- `ggml-large.bin` is the new v3 model
- `ggml-large-v2.bin` is the old v2 model

```bash
./models/download-ggml-model.sh large
```

---

This should be ready to merge.

I did some anecdotal tests using the audio samples in this repo and seems like v3 performs worse than v2 on them. It repeats lines quite often. Could be a problem on `whisper.cpp` side, though I ran one of the audio samples with the OG whisper and it repeats in a similar way:

```bash
$ ▶ whisper samples/hp0.wav --model large
/opt/homebrew/lib/python3.11/site-packages/whisper/transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
Detected language: English
[00:00.000 --> 00:11.840]  Henry F. Phillips, from Wikipedia, the free encyclopedia, at en.wikipedia.org
[00:11.840 --> 00:26.140]  Henry F. Phillips, 1890-1958
[00:26.140 --> 00:38.160]  A U.S. businessman from Portland, Oregon, has the honor of having the Phillips head screw and screwdriver named after him.
[00:39.280 --> 00:52.120]  The importance of the cross-head screw design lies in its self-centering property, useful on automated production lines that use powered screwdrivers.
[00:53.760 --> 00:56.120]  Phillips' major contribution was in...
[00:56.140 --> 01:04.640]  driving the cross-head concept forward, to the point where it was adopted by screwmakers and automobile companies.
[01:05.580 --> 01:10.380]  Although he received patents for the design in 1936,
[01:10.380 --> 01:17.720]  U.S. Patent No. 2,046,343
[01:17.720 --> 01:24.100]  U.S. Patents 2,046,837
[01:24.100 --> 01:25.380]  to 2,046,837
[01:26.140 --> 01:30.100]  to 2,046,842
[01:30.100 --> 01:32.340]  to 2,046,840
[01:32.340 --> 01:38.160]  to 2,046,840
[01:38.160 --> 01:47.880]  The American Screw Company was responsible for devising a means of manufacturing the Life FAQ function of Phillips hard come to proving praise by itsọi
[01:47.880 --> 01:50.960]  and licensed their method.
[01:50.960 --> 01:53.580]  Other screw makers of the 1930s dismissed the Phillips concept since...
[01:53.580 --> 01:55.500]  Other screw makers of the 1930s dismissed the Phillips concept since...
[01:55.500 --> 01:56.000]  Other screw makers of the 1930s dismissed the Phillips concept since...
[01:56.000 --> 02:02.240]  since it calls for a relatively complex, recessed socket shape in the head of the screw,
[02:03.080 --> 02:08.160]  as distinct from the simple milled slot of a slotted-type screw.
[02:08.740 --> 02:17.740]  The Phillips Screw Company and the American Screw Company went on to devise the posidrive screw,
[02:18.420 --> 02:25.260]  which differs from the Phillips in that it is designed to accommodate greater torque than the Phillips.
[02:26.000 --> 02:32.920]  An image accompanied this article, captioned, Phillips Screw Head.
[02:34.400 --> 02:39.440]  The following is an infobox which accompanies this article.
[02:40.660 --> 02:45.660]  Infobox, part of the series on screw drive types.
[02:47.160 --> 02:51.560]  Slotted, commonly, erroneously, flathead.
[02:52.820 --> 02:55.220]  Phillips, crosshead.
```

Anyway, we can't make any conclusions based on this single case, so will merge this for now and see what people report.

### CODE REVIEW

**Comment by ggerganov** [comment]
I cannot push to HuggingFace - any idea what is wrong?

```bash
git push
batch response: Authorization error. B | 0 B/s                                                                                                                                                                                                                                             
Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done.
error: failed to push some refs to 'https://huggingface.co/ggerganov/whisper.cpp'
```

I have created a write access token and have used `huggingface-cli login`, but it keep rejecting

**Comment by neurostar** [comment]
Thanks for quickly supporting v3 model! 
Tested in m2 macbook air, works great with metal (fp16, q5)
coreml conversion do not work yet. huggingface transformers need to updated (they just commit patch).

**Comment by LeiHao0** [comment]
I found the same that v3 repeats more than v2, even with VAD audios.

@ArabCoders also mentioned it duplicates more in Japanese under the official whisper repo in here.
https://github.com/openai/whisper/discussions/1762
It seems something wrong inside the model, and hope it can be fixed soon. Currently I rollback to v2.

Again, thank you for the quick support on v3 model and keep the v2 as well. This is the only one whisper project that works like a charm on my Mac Studio with Metal/MPS and even CoreML enabled!

**Comment by monk1337** [comment]
Awesome, thanks for quick support ;)

**Comment by emcodem** [comment]
Also in my first tests i found that, V3 large repeats or hallucinates a LOT more than V2. Not sure if it was a good idea that the V3 model is now the default large model - at least not without the obviously needed changes that mitigate the new repetitions

**Pull request merged**
