### PR TITLE
java bindings

### PR DESCRIPTION
**Pull request by nalbion**
@ggerganov I've tested `fullTranscribe()` and `getTextSegment()` on Windows and Ubuntu.

```
git clone https://github.com/nalbion/whisper.cpp.git
cd whisper.cpp/bindings/java
git checkout feature/java-bindings

mkdir build
pushd build
cmake ..
cmake --build .
popd

./gradlew test
```

> And so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

**Comment by nalbion** [comment]
@ggerganov can you update the github workshops to build and publish to maven central please?

**Comment by nalbion** [comment]
...it should build the libs for Mac, Linux and Windows and then run the gradle build which will emebed the libs into the jar

**Comment by ggerganov** [comment]
Won't have time to do that anytime soon - I would gladly accept a PR with this change

**Comment by nalbion** [comment]
It was easier to fix my implementation 😅

https://github.com/ggerganov/whisper.cpp/pull/944

**Pull request merged**
