### PR TITLE
Feature/java bindings2

### PR DESCRIPTION
**Pull request by nalbion**
I've updated the java bindings to directly use the `whisper` library. 

@ggerganov you'll have to define `secrets.OSSRH_USERNAME` and `secrets.OSSRH_TOKEN` - if you haven't already, you'd need to create an account at https://s01.oss.sonatype.org

### CODE REVIEW

**Comment by nalbion** [comment]
@ggerganov I'm trying to find where the Linux & Mac shared libraries are written to so that I can include them in the jar.

https://github.com/ggerganov/whisper.cpp/actions/runs/5041197583/jobs/9040679050#step:4:77

**Comment by ggerganov** [comment]
> @ggerganov you'll have to define `secrets.OSSRH_USERNAME` and `secrets.OSSRH_TOKEN` - if you haven't already, you'd need to create an account at https://s01.oss.sonatype.org

Is there a way to avoid this step? I don't want to make an account

> @ggerganov I'm trying to find where the Linux & Mac shared libraries are written to so that I can include them in the jar.
> 
> https://github.com/ggerganov/whisper.cpp/actions/runs/5041197583/jobs/9040679050#step:4:77

There are no pre-built libraries for Linux and Mac.
One has to build them locally so that the build can utilize the native instruction set

**Comment by nalbion** [comment]
I've removed the references to the mac/linux libs.

It would help the maven community if the library could be published to a repository.

GitHub have their own repository, but annoyingly you need to be authenticated to download public artifacts.
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry

**Comment by ggerganov** [comment]
> It would help the maven community if the library could be published to a repository.

Let me know if there is anything that I can do - I'm not familiar with the ecosystem and not sure how this works.
I'm okay to add you as a collaborator to `whisper.cpp` if this would help

The Java CI is still failing

**Comment by nalbion** [comment]
I've fixed the Java build.

The process for deploying (and getting setup up) is a bit tedious, but documented here - https://central.sonatype.org/publish/publish-guide/#initial-setup

You need to 

- Create a JIRA account for Sonatype - https://issues.sonatype.org/secure/Signup!default.jspa
- Create a new project ticket - https://issues.sonatype.org/secure/CreateIssue.jspa?pid=10134&issuetype=21
  - group ID: io.github.ggerganov
  - usernames: yourself and me (nalbion)
  - add credentials as GitHub project secrets.

For each deployment one of us needs to go into https://s01.oss.sonatype.org/#view-repositories;staging~browseindex
and "close" the release.

**Review by ggerganov — APPROVED** [review]
Fell free to merge this when ready (make sure to squash the commits)

I'll look into the account creation later - hope I don't forget

**Comment by nalbion** [comment]
Did you manage to create an account at Maven Central @ggerganov ? If you do that much and add your credentials as project secrets, give me your user ID I could do the rest and include you in the list of authorised publishers.

**Comment by ggerganov** [comment]
I think it is ready

image

image

**Comment by nalbion** [comment]
Great @ggerganov , now you just need to add your `OSSRH_USERNAME` and `OSSRH_TOKEN` as secret env vars in the GitHub repo settings and uncomment these lines (and move them back into `java`:

https://github.com/ggerganov/whisper.cpp/blob/master/.github/workflows/build.yml#L448

**Comment by ggerganov** [comment]
Not sure how to obtain the `OSSRH_USERNAME` and `OSSRH_TOKEN`

Do I need to follow these steps?

image

**Comment by nalbion** [comment]
I believe it's the username & password that you used to log into their Jira system.

Alternatively, you could also create a token - https://issues.sonatype.org/secure/ViewProfile.jspa?selectedTab=com.atlassian.pats.pats-plugin:jira-user-personal-access-tokens

Once the GitHub pipeline runs, one of use needs to go through this manual processs - https://central.sonatype.org/publish/release/#distribution-management-and-authentication

**Comment by ggerganov** [comment]
Let's see if it works: https://github.com/ggerganov/whisper.cpp/pull/1228

**Comment by nalbion** [comment]
@ggerganov sorry, I missed your question earlier. Yes, you will need to create a GitHub repository "OSSRH-94491" and then re-open the ticket https://issues.sonatype.org/browse/OSSRH-94491

(soon after you should be able to delete the GitHub repo)

**Pull request merged**
