### PR TITLE
Skip mm_mul kernel functions additions if on Intel

### PR DESCRIPTION
**Pull request by nchudleigh**
Tempfix for issue detailed here #1292

### CODE REVIEW

**Comment by jhen0409** [comment]
It's also related to https://github.com/ggerganov/llama.cpp/issues/2965, there may be more related issues in llama.cpp.

**Review by bobqianic — APPROVED** [review]

**Comment by bobqianic** [comment]
It looks good, but this is making encoding really slow.

**Comment by nchudleigh** [comment]
Otherwise, doesnt seem to work with intel at all. I wonder if its possible to write patches for the kernels.

**Comment by nchudleigh** [comment]
@ggerganov @bobqianic I dont feel confident in this merge, feels like the fix should be more elegant / actually fix the issue. What do you think?

**Comment by bobqianic** [comment]
> I dont feel confident in this merge, feels like the fix should be more elegant / actually fix the issue.

Agree.

**Comment by ggerganov** [comment]
I'm not sure what is the best approach here.

@nchudleigh Does using Metal provide significant speed-up compared to running on the CPU for Mac Intel?
I am considering disabling Metal all together for Mac Intel if it does not offer a significant benefit

**Comment by nchudleigh** [comment]
@ggerganov I missed this entirely!  

Hard to say whether it does or not... because the functions are missing I am not sure if the speed is improved or not. Probably depends on the GPU that is available.

**Comment by bobqianic** [comment]
I've reopened this PR after noticing that @ggerganov addressed a similar issue in [#3524](https://github.com/ggerganov/llama.cpp/pull/3524). Instead of introducing a new kernel, he chose to disable the buggy kernels on older devices as a fix. We have two choices moving forward:

1. Wait for the next ggml sync.
2. Merge this PR into master directly.

```metal
        if ([ctx->device supportsFamily:MTLGPUFamilyApple7]) {
            GGML_METAL_ADD_KERNEL(mul_mm_f32_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_f16_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q4_0_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q8_0_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q4_1_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q2_K_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q3_K_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q4_K_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q5_K_f32);
            GGML_METAL_ADD_KERNEL(mul_mm_q6_K_f32);
        }
```

**Comment by z11h** [comment]
@ggerganov any idea when the next GGML sync will be? thank you :)

**Comment by ggerganov** [comment]
Yup, let's try to fix this as part of #1422

**Pull request closed without merging**
