### PR TITLE
whisper : fix bench regression

### PR DESCRIPTION
**Pull request by ggerganov**
close: #1272 #1273 

@bobqianic @dereklll @nchudleigh

Can you try this branch and show me the results of the following command compared to 6780c98e193c19decb99157496c74046dd0e4aac:

```bash
make clean
make -j
./extra/bench-all.sh
```

Here is mine on M2 Ultra:

- 6780c98e193c19decb99157496c74046dd0e4aac

```java
$ ./extra/bench-all.sh
Usage: ./bench.sh [n_threads] [encoder-only]

Running memcpy benchmark

memcpy: 52.23 GB/s (1 thread)
sum:    -536871564.000000

Running ggml_mul_mat benchmark with 4 threads

  64 x   64: Q4_0     9.1 GFLOPS (128 runs) | Q4_1     9.0 GFLOPS (128 runs)
  64 x   64: Q5_0     9.4 GFLOPS (128 runs) | Q5_1    11.4 GFLOPS (128 runs) | Q8_0    16.8 GFLOPS (128 runs)
  64 x   64: F16     16.0 GFLOPS (128 runs) | F32     16.4 GFLOPS (128 runs)
 128 x  128: Q4_0   105.3 GFLOPS (128 runs) | Q4_1    96.3 GFLOPS (128 runs)
 128 x  128: Q5_0   103.9 GFLOPS (128 runs) | Q5_1   103.1 GFLOPS (128 runs) | Q8_0   107.8 GFLOPS (128 runs)
 128 x  128: F16    109.3 GFLOPS (128 runs) | F32    113.8 GFLOPS (128 runs)
 256 x  256: Q4_0   451.1 GFLOPS (128 runs) | Q4_1   396.9 GFLOPS (128 runs)
 256 x  256: Q5_0   442.1 GFLOPS (128 runs) | Q5_1   450.8 GFLOPS (128 runs) | Q8_0   469.8 GFLOPS (128 runs)
 256 x  256: F16    490.6 GFLOPS (128 runs) | F32    508.1 GFLOPS (128 runs)
 512 x  512: Q4_0  1021.9 GFLOPS (128 runs) | Q4_1   936.9 GFLOPS (128 runs)
 512 x  512: Q5_0  1138.6 GFLOPS (128 runs) | Q5_1  1135.5 GFLOPS (128 runs) | Q8_0  1019.1 GFLOPS (128 runs)
 512 x  512: F16   1198.5 GFLOPS (128 runs) | F32   1530.6 GFLOPS (128 runs)
1024 x 1024: Q4_0  1817.3 GFLOPS (128 runs) | Q4_1  1628.3 GFLOPS (128 runs)
1024 x 1024: Q5_0  1816.7 GFLOPS (128 runs) | Q5_1  1899.6 GFLOPS (128 runs) | Q8_0  1772.0 GFLOPS (128 runs)
1024 x 1024: F16   2044.1 GFLOPS (128 runs) | F32   2410.2 GFLOPS (128 runs)
2048 x 2048: Q4_0  3302.0 GFLOPS (128 runs) | Q4_1  2883.1 GFLOPS (128 runs)
2048 x 2048: Q5_0  3076.9 GFLOPS (128 runs) | Q5_1  3178.2 GFLOPS (128 runs) | Q8_0  3397.5 GFLOPS (128 runs)
2048 x 2048: F16   3308.1 GFLOPS (128 runs) | F32   3420.7 GFLOPS (128 runs)
4096 x 4096: Q4_0  3391.7 GFLOPS ( 25 runs) | Q4_1  3163.5 GFLOPS ( 24 runs)
4096 x 4096: Q5_0  3339.2 GFLOPS ( 25 runs) | Q5_1  3355.0 GFLOPS ( 25 runs) | Q8_0  3282.0 GFLOPS ( 24 runs)
4096 x 4096: F16   3453.9 GFLOPS ( 26 runs) | F32   3545.1 GFLOPS ( 26 runs)

Running benchmark for all models
This can take a while!

| CPU | OS | Config | Model | Th | Load | Enc. | Commit |
| --- | -- | ------ | ----- | -- | ---- | ---- | ------ |
| <todo> | <todo> |  NEON BLAS | tiny | 4 | 45 | 161 | 6780c98 |
| <todo> | <todo> |  NEON BLAS | base | 4 | 61 | 266 | 6780c98 |
| <todo> | <todo> |  NEON BLAS | small | 4 | 146 | 849 | 6780c98 |
| <todo> | <todo> |  NEON BLAS | medium | 4 | 423 | 2193 | 6780c98 |
| <todo> | <todo> |  NEON BLAS | large | 4 | 842 | 3617 | 6780c98 |
```

- this PR

```java
$ ▶ ./extra/bench-all.sh
Usage: ./bench.sh [n_threads] [encoder-only]

Running memcpy benchmark

memcpy: 52.33 GB/s (1 thread)
sum:    -536871564.000000

Running ggml_mul_mat benchmark with 4 threads

  64 x   64: Q4_0     8.0 GFLOPS (128 runs) | Q4_1     7.9 GFLOPS (128 runs)
  64 x   64: Q5_0     8.0 GFLOPS (128 runs) | Q5_1    13.0 GFLOPS (128 runs) | Q8_0    14.3 GFLOPS (128 runs)
  64 x   64: F16     14.5 GFLOPS (128 runs) | F32     14.9 GFLOPS (128 runs)
 128 x  128: Q4_0    86.0 GFLOPS (128 runs) | Q4_1    89.3 GFLOPS (128 runs)
 128 x  128: Q5_0    93.4 GFLOPS (128 runs) | Q5_1    96.7 GFLOPS (128 runs) | Q8_0    78.2 GFLOPS (128 runs)
 128 x  128: F16    102.4 GFLOPS (128 runs) | F32    102.2 GFLOPS (128 runs)
 256 x  256: Q4_0   433.2 GFLOPS (128 runs) | Q4_1   386.7 GFLOPS (128 runs)
 256 x  256: Q5_0   421.1 GFLOPS (128 runs) | Q5_1   430.3 GFLOPS (128 runs) | Q8_0   447.3 GFLOPS (128 runs)
 256 x  256: F16    471.6 GFLOPS (128 runs) | F32    485.0 GFLOPS (128 runs)
 512 x  512: Q4_0   681.7 GFLOPS (128 runs) | Q4_1   769.8 GFLOPS (128 runs)
 512 x  512: Q5_0   797.1 GFLOPS (128 runs) | Q5_1   808.3 GFLOPS (128 runs) | Q8_0   680.8 GFLOPS (128 runs)
 512 x  512: F16    780.8 GFLOPS (128 runs) | F32   1066.9 GFLOPS (128 runs)
1024 x 1024: Q4_0  1130.5 GFLOPS (128 runs) | Q4_1   910.1 GFLOPS (128 runs)
1024 x 1024: Q5_0  1176.1 GFLOPS (128 runs) | Q5_1  1175.4 GFLOPS (128 runs) | Q8_0   994.8 GFLOPS (128 runs)
1024 x 1024: F16   1579.1 GFLOPS (128 runs) | F32   1799.8 GFLOPS (128 runs)
2048 x 2048: Q4_0  3193.6 GFLOPS (128 runs) | Q4_1  2765.2 GFLOPS (128 runs)
2048 x 2048: Q5_0  3020.0 GFLOPS (128 runs) | Q5_1  3094.0 GFLOPS (128 runs) | Q8_0  3188.2 GFLOPS (128 runs)
2048 x 2048: F16   3399.7 GFLOPS (128 runs) | F32   3406.8 GFLOPS (128 runs)
4096 x 4096: Q4_0  3345.7 GFLOPS ( 25 runs) | Q4_1  3088.3 GFLOPS ( 23 runs)
4096 x 4096: Q5_0  3256.4 GFLOPS ( 24 runs) | Q5_1  3309.9 GFLOPS ( 25 runs) | Q8_0  3348.8 GFLOPS ( 25 runs)
4096 x 4096: F16   3371.8 GFLOPS ( 25 runs) | F32   3473.8 GFLOPS ( 26 runs)

Running benchmark for all models
This can take a while!

| CPU | OS | Config | Model | Th | Load | Enc. | Commit |
| --- | -- | ------ | ----- | -- | ---- | ---- | ------ |
| <todo> | <todo> |  NEON BLAS | tiny | 4 | 39 | 104 | 39c4fc5 |
| <todo> | <todo> |  NEON BLAS | base | 4 | 57 | 200 | 39c4fc5 |
| <todo> | <todo> |  NEON BLAS | small | 4 | 147 | 594 | 39c4fc5 |
| <todo> | <todo> |  NEON BLAS | medium | 4 | 425 | 1649 | 39c4fc5 |
| <todo> | <todo> |  NEON BLAS | large | 4 | 846 | 2827 | 39c4fc5 |
```

- after `09a6325de56856490ae9046bf0030ceedc04028a`

```java
  64 x   64: Q4_0     9.1 GFLOPS (128 runs) | Q4_1     9.1 GFLOPS (128 runs)
  64 x   64: Q5_0     9.2 GFLOPS (128 runs) | Q5_1    11.8 GFLOPS (128 runs) | Q8_0    16.5 GFLOPS (128 runs)
  64 x   64: F16     16.9 GFLOPS (128 runs) | F32     16.3 GFLOPS (128 runs)
 128 x  128: Q4_0   102.0 GFLOPS (128 runs) | Q4_1    96.9 GFLOPS (128 runs)
 128 x  128: Q5_0   101.1 GFLOPS (128 runs) | Q5_1   104.8 GFLOPS (128 runs) | Q8_0   107.3 GFLOPS (128 runs)
 128 x  128: F16    110.0 GFLOPS (128 runs) | F32    112.2 GFLOPS (128 runs)
 256 x  256: Q4_0   456.4 GFLOPS (128 runs) | Q4_1   399.4 GFLOPS (128 runs)
 256 x  256: Q5_0   446.2 GFLOPS (128 runs) | Q5_1   446.3 GFLOPS (128 runs) | Q8_0   473.0 GFLOPS (128 runs)
 256 x  256: F16    490.1 GFLOPS (128 runs) | F32    508.5 GFLOPS (128 runs)
 512 x  512: Q4_0   963.2 GFLOPS (128 runs) | Q4_1   893.9 GFLOPS (128 runs)
 512 x  512: Q5_0  1092.0 GFLOPS (128 runs) | Q5_1  1067.5 GFLOPS (128 runs) | Q8_0   960.0 GFLOPS (128 runs)
 512 x  512: F16   1125.6 GFLOPS (128 runs) | F32   1493.3 GFLOPS (128 runs)
1024 x 1024: Q4_0  1816.4 GFLOPS (128 runs) | Q4_1  1550.5 GFLOPS (128 runs)
1024 x 1024: Q5_0  1799.5 GFLOPS (128 runs) | Q5_1  1895.6 GFLOPS (128 runs) | Q8_0  1722.0 GFLOPS (128 runs)
1024 x 1024: F16   2000.7 GFLOPS (128 runs) | F32   2349.3 GFLOPS (128 runs)
2048 x 2048: Q4_0  3290.1 GFLOPS (128 runs) | Q4_1  2850.6 GFLOPS (128 runs)
2048 x 2048: Q5_0  3127.4 GFLOPS (128 runs) | Q5_1  3181.2 GFLOPS (128 runs) | Q8_0  3300.4 GFLOPS (128 runs)
2048 x 2048: F16   3330.3 GFLOPS (128 runs) | F32   3458.5 GFLOPS (128 runs)
4096 x 4096: Q4_0  3065.2 GFLOPS ( 23 runs) | Q4_1  3011.1 GFLOPS ( 22 runs)
4096 x 4096: Q5_0  3243.4 GFLOPS ( 24 runs) | Q5_1  3183.4 GFLOPS ( 24 runs) | Q8_0  3260.7 GFLOPS ( 24 runs)
4096 x 4096: F16   3297.0 GFLOPS ( 24 runs) | F32   3418.8 GFLOPS ( 25 runs)

Running benchmark for all models
This can take a while!

| CPU | OS | Config | Model | Th | Load | Enc. | Commit |
| --- | -- | ------ | ----- | -- | ---- | ---- | ------ |
| <todo> | <todo> |  NEON BLAS | tiny | 4 | 38 | 106 | 09a6325 |
| <todo> | <todo> |  NEON BLAS | base | 4 | 57 | 203 | 09a6325 |
| <todo> | <todo> |  NEON BLAS | small | 4 | 147 | 593 | 09a6325 |
| <todo> | <todo> |  NEON BLAS | medium | 4 | 425 | 1733 | 09a6325 |
| <todo> | <todo> |  NEON BLAS | large | 4 | 843 | 2895 | 09a6325 |
```

### CODE REVIEW

**Comment by bobqianic** [comment]
OK

**Comment by dereklll** [comment]
[39c4fc5](https://github.com/ggerganov/whisper.cpp/pull/1275/commits/39c4fc59dd72cd941bbbdeb470162fb42edaea15)
./extra/bench-all.sh                     
Usage: ./bench.sh [n_threads] [encoder-only]

Running memcpy benchmark

memcpy: 51.55 GB/s (1 thread)
sum:    -536871564.000000

Running ggml_mul_mat benchmark with 4 threads

  64 x   64: Q4_0     8.3 GFLOPS (128 runs) | Q4_1     8.8 GFLOPS (128 runs)
  64 x   64: Q5_0     8.7 GFLOPS (128 runs) | Q5_1    10.1 GFLOPS (128 runs) | Q8_0    14.2 GFLOPS (128 runs)
  64 x   64: F16     13.8 GFLOPS (128 runs) | F32     14.2 GFLOPS (128 runs)
 128 x  128: Q4_0    93.3 GFLOPS (128 runs) | Q4_1    86.5 GFLOPS (128 runs)
 128 x  128: Q5_0    92.4 GFLOPS (128 runs) | Q5_1    92.4 GFLOPS (128 runs) | Q8_0    96.1 GFLOPS (128 runs)
 128 x  128: F16     98.8 GFLOPS (128 runs) | F32    101.9 GFLOPS (128 runs)
 256 x  256: Q4_0   421.7 GFLOPS (128 runs) | Q4_1   375.7 GFLOPS (128 runs)
 256 x  256: Q5_0   409.0 GFLOPS (128 runs) | Q5_1   421.4 GFLOPS (128 runs) | Q8_0   436.2 GFLOPS (128 runs)
 256 x  256: F16    458.4 GFLOPS (128 runs) | F32    477.8 GFLOPS (128 runs)
 512 x  512: Q4_0   813.5 GFLOPS (128 runs) | Q4_1   781.8 GFLOPS (128 runs)
 512 x  512: Q5_0   915.9 GFLOPS (128 runs) | Q5_1   926.3 GFLOPS (128 runs) | Q8_0   771.6 GFLOPS (128 runs)
 512 x  512: F16    890.6 GFLOPS (128 runs) | F32   1211.5 GFLOPS (128 runs)
1024 x 1024: Q4_0  1352.4 GFLOPS (128 runs) | Q4_1   905.6 GFLOPS (128 runs)
1024 x 1024: Q5_0  1328.9 GFLOPS (128 runs) | Q5_1  1436.4 GFLOPS (128 runs) | Q8_0  1087.4 GFLOPS (128 runs)
1024 x 1024: F16   1364.2 GFLOPS (128 runs) | F32   1740.5 GFLOPS (128 runs)
2048 x 2048: Q4_0  3228.5 GFLOPS (128 runs) | Q4_1  2799.6 GFLOPS (128 runs)
2048 x 2048: Q5_0  2968.0 GFLOPS (128 runs) | Q5_1  3094.5 GFLOPS (128 runs) | Q8_0  3214.1 GFLOPS (128 runs)
2048 x 2048: F16   3410.8 GFLOPS (128 runs) | F32   3516.9 GFLOPS (128 runs)
4096 x 4096: Q4_0  3350.7 GFLOPS ( 25 runs) | Q4_1  3132.2 GFLOPS ( 23 runs)
4096 x 4096: Q5_0  3292.5 GFLOPS ( 24 runs) | Q5_1  3289.1 GFLOPS ( 24 runs) | Q8_0  3346.0 GFLOPS ( 25 runs)
4096 x 4096: F16   3368.1 GFLOPS ( 25 runs) | F32   3477.8 GFLOPS ( 26 runs)

Running benchmark for all models
This can take a while!

| CPU | OS | Config | Model | Th | Load | Enc. | Commit |
| --- | -- | ------ | ----- | -- | ---- | ---- | ------ |
| <todo> | <todo> |  NEON BLAS | base | 4 | 58 | 205 | 39c4fc5 |

**Comment by dereklll** [comment]
done.













--

Best Regards,

刘龙龙
Derek Liu
TEl:132 6290 0998
E-Mail: ***@***.***





在 2023-09-12 16:28:23，"bobqianic" ***@***.***> 写道：

OK

**Comment by ggerganov** [comment]
Thank you for the data. After commit 09a6325de56856490ae9046bf0030ceedc04028a that I just pushed, the performance with OpenBLAS should now be restored

**Comment by bobqianic** [comment]
> Thank you for the data. After commit [09a6325](https://github.com/ggerganov/whisper.cpp/commit/09a6325de56856490ae9046bf0030ceedc04028a) that I just pushed, the performance with OpenBLAS should now be restored

Thanks!

**Pull request merged**
