### PR TITLE
Add Android sample

### PR DESCRIPTION
**Pull request by Digipom**
A sample Android app using [whisper.cpp](https://github.com/ggerganov/whisper.cpp/) to do voice-to-text transcriptions.

To use:

1. Select a model from the [whisper.cpp repository](https://github.com/ggerganov/whisper.cpp/tree/master/models).[^1]
2. Copy the model to the "app/src/main/assets/models" folder.
3. Select a sample audio file (for example, [jfk.wav](https://github.com/ggerganov/whisper.cpp/raw/master/samples/jfk.wav)).
4. Copy the sample to the "app/src/main/assets/samples" folder.
5. Select the "release" active build variant, and use Android Studio to run and deploy to your device.
[^1]: I recommend the tiny or base models for running on an Android device.

### CODE REVIEW

**Comment by ggerganov** [comment]
Awesome work! Thank you so much!
It works very well and this is exactly what I imagined for a demo application.

Before merging, I want to find a way to avoid the duplicated `ggml`/`whisper` source files in the example dir. Maybe some symbolic links, or some CMakeLists.txt updates. Not sure yet. If you have ideas how to avoid the duplication - let me know.

**Comment by Digipom** [comment]
Done! :) Let me know how this looks.

**Comment by ggerganov** [comment]
@Digipom Great job!

I created a discussion here: https://github.com/ggerganov/whisper.cpp/discussions/283
And I also referenced your example from the main README of the project. Thanks!

**Comment by Digipom** [comment]
Thanks to you for creating this project! :)

**Pull request merged**
