### PR TITLE
Change ggml.c to make it compatible with C++ compilers.

### PR DESCRIPTION
**Pull request by Alejandro-FA**
In a small cross-platform mobile project that I'm working on I've been forced to compile `ggml.c` with a C++ compiler (`clang++`). This has exposed some minor incompatibilities of `ggml.c` with C++ compilers, which can be easily solved.

### CODE REVIEW

**Comment by fire** [comment]
Are the binary files supposed to be included?

**Comment by Alejandro-FA** [comment]
The binary files were not supposed to be included. I have deleted them from the branch, sorry for the trouble.

**Comment by fire** [comment]
Do you know if whisper.cpp has a 1 merge commit policy? The binary files are still in the pull request. You probably need to squash.

**Comment by Alejandro-FA** [comment]
> Do you know if whisper.cpp has a 1 merge commit policy? The binary files are still in the pull request. You probably need to squash.

I don't know if they have such a policy, but as far as I understand it is a decision to take when merging, not now.

Are you sure about the binary files? I only see 1 file changed in the pull request.

**Comment by ziegenberg** [comment]
Commit ec6c2cd79f15b0b477d1640141b05af07dc7abdd, which is part of this PR, does indeed include the binary files. You could squash your commits and force-push.

**Pull request closed without merging**
