### PR TITLE
GPU support via NVBLAS

### PR DESCRIPTION
**Pull request by ggerganov**
ref #220 

WIP IN PROGRESS

### CODE REVIEW

**Comment by Green-Sky** [comment]
NVBLAS or cuBLAS ?

**Comment by dakk** [comment]
let me know if someone else is working on this feature; otherwise I'll put my hands on it

**Comment by DanielusG** [comment]
> let me know if someone else is working on this feature; otherwise I'll put my hands on it
> 
> EDIT: I was to curious and I implemented it already: https://github.com/dakk/whisper.cpp using cublas. Let me know if I can create the PR.

I want to try your code, what should I do? I've cloned your repo and i've the ggml model. And now?

**Comment by dakk** [comment]
> > let me know if someone else is working on this feature; otherwise I'll put my hands on it
> > EDIT: I was to curious and I implemented it already: https://github.com/dakk/whisper.cpp using cublas. Let me know if I can create the PR.
> 
> I want to try your code, what should I do? I've cloned your repo and i've the ggml model. And now? (i'm on linux if it can be relevant)

```
mkdir build
cd build
cmake .. -DWHISPER_SUPPORT_CUBLAS=TRUE
make
cd ..
./build/bin/main -m models/ggml-tiny.en.bin -f samples/jfk.wav
``` 
```

**Comment by dakk** [comment]
> @dakk I can confirm it works well with my GPU, but I notice one thing. With standard whisper I can use medium model with my RTX 2060 (6GB). Now with whisper.cpp CUDA enabled it runs out of memory.

Forgot to free some memory; now should run fine.

```git pull && cd build && make```

**Comment by vakkov** [comment]
@DanielusG https://bitbucket.org/sensika/whisper.cpp/branch/cublas

medium consumes 580 MB of vmem for me:
`WHISPER_CUBLAS=1 make `

**Comment by DanielusG** [comment]
> > @dakk I can confirm it works well with my GPU, but I notice one thing. With standard whisper I can use medium model with my RTX 2060 (6GB). Now with whisper.cpp CUDA enabled it runs out of memory.
> 
> Forgot to free some memory; now should run fine.
> 
> `git pull && cd build && make`

Yes! it work very well. Like a charm :)

**Comment by ggerganov** [comment]
I will add the cuBLAS support from the `llama.cpp` repo to whisper.cpp for the next release

**Comment by ggerganov** [comment]
Hi all, I am backporting the cuBLAS support from `llama.cpp` here: https://github.com/ggerganov/whisper.cpp/pull/834

Unfortunately, I don't observe significant speed-up. It's quite small actually
@vakkov Will appreciate if you take a look if I did something wrong. Maybe it is just my system and it actually works better on others - not sure

**Comment by ggerganov** [comment]
Superseded by https://github.com/ggerganov/whisper.cpp/pull/834

**Pull request closed without merging**
