### PR TITLE
Use pkg-config for OpenBLAS

### PR DESCRIPTION
**Pull request by przemoc**
Information can be found in commit messages. There are various tweaks done along the way.
Makefile changes are simpler. CMakeLists.txt changes are a bit more complex.

This may not be perfect, but overall should be a noticeable improvement over what we had before regarding OpenBLAS handling.
`OPENBLAS_PATH` remains supported. `BLAS_HOME` is no longer supported. I don't believe in kitchen sink approach to support any possible ad hoc conventions created out there. As long as we expose sufficient knobs to control build process, downstream can adapt appropriately.

Most likely some CI checks will fail. Will try to fix it some other day. MacOS may blow up as usual.
(My CMake experience is small, and the more I learn about it, the less I like it. And I do not want to rewrite some of the batteries they provide...).

I will also appreciate some testing. I did limited testing in one of MSYS2 environments (UCRT64), Alpine Linux 3.18.5 (w/ `WHISPER_OPENBLAS_INTERFACE64=0`), Ubuntu 22.04.

---

It's not clear to me if `WHISPER_OPENBLAS_INTERFACE64` should be really enabled by default, I just followed existing intention expressed via `set(BLA_SIZEOF_INTEGER 8)`. I think having it disabled (using OpenBLAS w/ 32-bit interface) would be a better out of the box experience for most folks out there, but maybe I'm missing something?

Another thing, that I definitely do not intend to address in this PR, is support for OpenBLAS built w/ `SYMBOLSUFFIX=64_`, which I have not yet researched how it should be dealt. That's also a reason why OpenBLAS w/ 32-bit interface is a "safer" choice by default.

### CODE REVIEW

**Comment by przemoc** [comment]
Capturing logs from failing steps in Windows builds for further analysis on some other day (as I don't know log retention policies here):

[windows-blas (Release, Win32, ON, ON) (pull_request)](https://github.com/ggerganov/whisper.cpp/actions/runs/7557496121/job/20576868802?pr=1778)
<details>
<summary>Configure</summary>

```
Run cmake -S . -B ./build -A Win32 -DCMAKE_BUILD_TYPE=Release -DWHISPER_OPENBLAS=ON -DCMAKE_LIBRARY_PATH="$env:OPENBLAS_PATH/lib" -DWHISPER_SDL2=ON -DWHISPER_CLBLAST=OFF
  cmake -S . -B ./build -A Win32 -DCMAKE_BUILD_TYPE=Release -DWHISPER_OPENBLAS=ON -DCMAKE_LIBRARY_PATH="$env:OPENBLAS_PATH/lib" -DWHISPER_SDL2=ON -DWHISPER_CLBLAST=OFF
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    ubuntu_image: ubuntu:22.04
    OPENBLAS_PATH: D:\a\whisper.cpp\whisper.cpp/blas
    SDL2_DIR: D:\a\whisper.cpp\whisper.cpp/SDL2-2.28.5/cmake
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.37.32826.1
-- The CXX compiler identification is MSVC 19.37.32826.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.43.0.windows.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
-- BLAS compatible library path provided
-- Libraries D:\a\whisper.cpp\whisper.cpp/blas/lib/openblas64.lib
-- Include dirs D:\a\whisper.cpp\whisper.cpp/blas/include
CMake Error at CMakeLists.txt:207 (message):
  BLAS library was not found.  Environment variable OPENBLAS_PATH misdefined.


-- Configuring incomplete, errors occurred!
Error: Process completed with exit code 1.
```

</details>

```
-- BLAS compatible library path provided
-- Libraries D:\a\whisper.cpp\whisper.cpp/blas/lib/openblas64.lib
-- Include dirs D:\a\whisper.cpp\whisper.cpp/blas/include
CMake Error at CMakeLists.txt:207 (message):
  BLAS library was not found.  Environment variable OPENBLAS_PATH misdefined.
```

[windows-blas (Release, x64, ON, ON) (pull_request)](https://github.com/ggerganov/whisper.cpp/actions/runs/7557496121/job/20576870202?pr=1778)
<details>
<summary>Configure</summary>

```
Run cmake -S . -B ./build -A x64 -DCMAKE_BUILD_TYPE=Release -DWHISPER_OPENBLAS=ON -DCMAKE_LIBRARY_PATH="$env:OPENBLAS_PATH/lib" -DWHISPER_SDL2=ON -DWHISPER_CLBLAST=ON
  cmake -S . -B ./build -A x64 -DCMAKE_BUILD_TYPE=Release -DWHISPER_OPENBLAS=ON -DCMAKE_LIBRARY_PATH="$env:OPENBLAS_PATH/lib" -DWHISPER_SDL2=ON -DWHISPER_CLBLAST=ON
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    ubuntu_image: ubuntu:22.04
    OPENBLAS_PATH: D:\a\whisper.cpp\whisper.cpp/blas
    SDL2_DIR: D:\a\whisper.cpp\whisper.cpp/SDL2-2.28.5/cmake
    CLBlast_DIR: D:\a\whisper.cpp\whisper.cpp/CLBlast-1.6.1-windows-x64/lib/cmake/CLBlast
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.37.32826.1
-- The CXX compiler identification is MSVC 19.37.32826.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.43.0.windows.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
-- BLAS compatible library path provided
-- Libraries D:\a\whisper.cpp\whisper.cpp/blas/lib/openblas64.lib
-- Include dirs D:\a\whisper.cpp\whisper.cpp/blas/include
CMake Error at CMakeLists.txt:207 (message):
  BLAS library was not found.  Environment variable OPENBLAS_PATH misdefined.


-- Configuring incomplete, errors occurred!
Error: Process completed with exit code 1.
```

</details>

```
-- BLAS compatible library path provided
-- Libraries D:\a\whisper.cpp\whisper.cpp/blas/lib/openblas64.lib
-- Include dirs D:\a\whisper.cpp\whisper.cpp/blas/include
CMake Error at CMakeLists.txt:207 (message):
  BLAS library was not found.  Environment variable OPENBLAS_PATH misdefined.
```

---

Passing builds from recent commit 1f50a7d29f85f221368e81201780e0c8dd631076 have:

```
-- Libraries D:\a\whisper.cpp\whisper.cpp/blas/lib/libopenblas.dll.a
```

(before this PR there were fewer things messaged related to OpenBLAS)

which makes me wonder what, where and how is built for Windows, because AFAIK `.dll.a` is not a native Windows thing (MSYS2 environments are closer to *nix than Windows, so `.dll.a` would be fine there). I may need to analyze environment setup steps in CI to better understand what's going on. I hope to be able to do that without MS tools (but in the worst case I may end up polluting my Windows by installing [Visual Studio](https://visualstudio.microsoft.com/downloads/) for the first time since ~20y or so).

Maybe some tweaks in CI config / workflow steps or actions will be also necessary to clean things up. Hard to tell at this stage.

**Comment by ggerganov** [comment]
Thanks for looking into this! I don't have access to Windows systems, so I won't be able to provide much help about the build process. But let me know if you hit any roadblocks along the way

**Comment by przemoc** [comment]
Sure, @ggerganov, appreciated!

@tamo, thank you for useful pointers and your PR (przemoc/whisper.cpp/pull/1) with suggested changes to my PR. Your changes seem to be overfit for particular environment and assumptions regarding OpenBLAS (similar sin that is present in whisper.cpp nowadays until my PR will improve that).

I didn't have time yet to investigate Windows build process in whisper.cpp and OpenBLAS builds, but just wanted to reply now regardless.

It's a shame if OpenBLAS really does use only MSYS2 and does not provide MSVC-based builds. Mixing MSVC and non-MSVC binaries is literally asking for trouble. It was true for msvcrt-based MinGW / MinGW-w64 and I suspect it's true for ucrt-based MinGW-w64. Well, at least for GCC, as CLANG actually aims for [MSVC compatibility](https://clang.llvm.org/docs/MSVCCompatibility.html), so it's safer to mix MSVC and CLANG binaries on Windows.

OpenBLAS's CI configuration does not necessarily reflect how assets added to releases are built, though. In workflows they build using both UCRT64 and CLANG64 (among other variants), but in each `.zip` file there is only one `.dll`, and it's not clear from which compiler it comes from. Maybe it's from MSVC after all? In CI they build with both `BINARY64=1` and `INTERFACE64=1` in UCRT64 and CLANG64.

`x64-64` started being provided in OpenBLAS v0.3.25. OpenBLAS prebuilt binaries variants are:
- `x86` - 32-bit build
- `x64` - 64-bit build
- `x64-64` - 64-bit build with `INTERFACE64=1`
  (`USE_64BITINT=1` exposed in openblas_config.h via _empty_ define `OPENBLAS_USE64BITINT`)

(surprisingly I didn't find anywhere clear information that I provided above, had to dig into differences between `.zip` files)

What is also sad is that their variants do not differ by any suffix for actual library, which is called `libopenblas.dll` in all cases. :( I was not aware of that. This means that using OpenBLAS prebuilt binaries may require extra logic vs rest of the world, i.e. *nix (including MSYS2 environments, where `libopenblas.so` and `libopenblas64.so` can coexist).

And those `.zip` files have both *nix-like `libopenblas.a` and "hybrid" `libopenblas.dll.a`, but also `libopenblas.lib` (I checked only filenames, have not analyzed their content), so revising whisper.cpp environment setup may be what's necessary here too.

My PR is meant to make stuff work in native Windows (MSVC), MSYS2 environment, and *nix, at least to the extent possible by what CMake provides (versus make that by convention is meant for *nix-like environments only, so don't have to bother with MSVC). MSYS2 started working with my changes, but I broke MSVC builds due to not spending any time with them and not being familiar with existing whisper.cpp build flow for Windows.

Regarding prefix, if everyone in Windows world builds OpenBLAS with `lib` in front (which is _not_ common for libraries in Windows) - to be investigated, then prefix for library can be hardcoded to `lib`.

Regarding suffix, they are different between MSVC, MSYS2 and *nix, so we cannot get rid of it.

Regarding FindBLAS, I already looked into it back then, and left various comments regarding it in the code.

IMHO CMake is not a good build solution, users are inclined to use its batteries, but they seem to be not well-maintained, and if you happen to have older CMake, which may have older versions of the modules, you're even more screwed. But it's unrealistic to expect anyone to support various CMake versions with varying degree of features their modules provide...

---

After spending as little time as necessary for writing this comment and glancing at OpenBLAS `.zip` files (and not really researching anything more yet), I think PR fails right now for Windows using CMake due to:

- not hardcoding `lib` prefix for OpenBLAS library
  (OpenBLAS prebuilt binaries deviate from native Windows conventions, which normally do not have prefixes for libraries)
- not hardcoding `WHISPER_BLAS_LIB=openblas` for MSVC
  (it has to be `openblas` regardless of `INTERFACE64` setting for OpenBLAS prebuilt binaries)
- defaulting to `WHISPER_OPENBLAS_INTERFACE64=on`
  (whisper.cpp is build with `x86` and `x64` OpenBLAS variants only)

I will do some quick fixes to address those fixes, but even if the build will successfully pass, please do not merge it yet, as I may need to think about it more whether we're achieving LGTM state where potential further tweaks can be done via separate PRs, or if some basic tweaks still need to be done before merging.

**Comment by przemoc** [comment]
Looks like GH checks are somehow stuck.
@ggerganov, is it something you're able to poke to make it run properly?

**Comment by avie41** [comment]
Hi @przemoc,
Thanks for your work!


I'm still trying to build the stream version of whisper.cpp.

As you seem to be working on Windows I wanted to know if you had already succeeded on your side?

Thanks for that

**Review by ggerganov — APPROVED** [review]

**Comment by przemoc** [comment]
Rebased and resolved minor merge conflict.

**Pull request merged**
